# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesado', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('distancia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CajaMedidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=15)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[(b'agua', b'agua'), (b'alcantarillado', b'alcantarillado')], max_length=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DiametroAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caja_medidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camposaguas.CajaMedidor')),
            ],
        ),
        migrations.CreateModel(
            name='Eliminacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[(b'agua', b'agua'), (b'alcantarillado', b'alcantarillado')], max_length=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empalme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('tipo_empalme', models.CharField(blank=True, choices=[(b'60', b'60'), (b'160', b'160'), (b'200', b'200')], max_length=3)),
                ('tipo_servicio_empalme', models.CharField(blank=True, choices=[(b'agua', b'agua'), (b'desague', b'desague')], max_length=8)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Excavacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[(b'agua', b'agua'), (b'desague', b'desague')], max_length=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PruebaHidraulica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[(b'agua', b'agua'), (b'alcantarillado', b'alcantarillado')], max_length=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Relleno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[(b'agua', b'agua'), (b'alcantarillado', b'alcantarillado')], max_length=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reposicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, choices=[(b'tierra', b'tierra'), (b'asfalto', b'asfalto'), (b'concreto', b'concreto')], max_length=15)),
                ('tipo', models.CharField(blank=True, choices=[(b'agua', b'agua'), (b'alcantarillado', b'alcantarillado')], max_length=15)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rotura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('tipo', models.CharField(blank=True, choices=[(b'agua', b'agua'), (b'alcantarillado', b'alcantarillado')], max_length=15)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tendido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(blank=True, choices=[(b'agua', b'agua'), (b'alcantarillado', b'alcantarillado')], max_length=15)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camposaguas.Reposicion')),
                ('rotura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camposaguas.Rotura')),
            ],
        ),
        migrations.CreateModel(
            name='Vereda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, choices=[(b'si', b'si'), (b'no', b'no')], max_length=2)),
                ('tipo', models.CharField(blank=True, choices=[(b'agua', b'agua'), (b'alcantarillado', b'alcantarillado')], max_length=15)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='diametroagua',
            name='tendido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camposaguas.Tendido'),
        ),
        migrations.AddField(
            model_name='agua',
            name='cama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camposaguas.Cama'),
        ),
        migrations.AddField(
            model_name='agua',
            name='diametro_agua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camposaguas.DiametroAgua'),
        ),
        migrations.AddField(
            model_name='agua',
            name='eliminacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camposaguas.Eliminacion'),
        ),
        migrations.AddField(
            model_name='agua',
            name='empalme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camposaguas.Empalme'),
        ),
        migrations.AddField(
            model_name='agua',
            name='excavacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camposaguas.Excavacion'),
        ),
        migrations.AddField(
            model_name='agua',
            name='pista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camposaguas.TipoPista'),
        ),
        migrations.AddField(
            model_name='agua',
            name='prueba_hidraulica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camposaguas.PruebaHidraulica'),
        ),
        migrations.AddField(
            model_name='agua',
            name='relleno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camposaguas.Relleno'),
        ),
        migrations.AddField(
            model_name='agua',
            name='vereda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camposaguas.Vereda'),
        ),
    ]
